tasks:
  install:
    name: Install dependencies
    command: |
      sbt update
    triggeredBy:
      - postDevcontainerStart

  build:
    name: Compile
    command: |
      sbt compile
    dependsOn:
      - install
    triggeredBy:
      - manual

  test:
    name: Run tests
    command: |
      sbt test
    dependsOn:
      - install
    triggeredBy:
      - manual

  coverage:
    name: Generate coverage report
    command: |
      sbt scct:test
    dependsOn:
      - install
    triggeredBy:
      - manual

services: {}
